/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as VirtualModelRouteImport } from './routes/virtual-model'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreRegisterRouteImport } from './routes/store.register'
import { Route as StorePackageRouteImport } from './routes/store.package'
import { Route as StoreItemsRouteImport } from './routes/store.items'
import { Route as StoreIdRouteImport } from './routes/store.$id'

const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualModelRoute = VirtualModelRouteImport.update({
  id: '/virtual-model',
  path: '/virtual-model',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRegisterRoute = StoreRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => StoreRoute,
} as any)
const StorePackageRoute = StorePackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => StoreRoute,
} as any)
const StoreItemsRoute = StoreItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => StoreRoute,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRouteWithChildren
  '/virtual-model': typeof VirtualModelRoute
  '/wardrobe': typeof WardrobeRoute
  '/store/$id': typeof StoreIdRoute
  '/store/items': typeof StoreItemsRoute
  '/store/package': typeof StorePackageRoute
  '/store/register': typeof StoreRegisterRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/virtual-model': typeof VirtualModelRoute
  '/wardrobe': typeof WardrobeRoute
  '/store/$id': typeof StoreIdRoute
  '/store/items': typeof StoreItemsRoute
  '/store/package': typeof StorePackageRoute
  '/store/register': typeof StoreRegisterRoute
  '/store': typeof StoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRouteWithChildren
  '/virtual-model': typeof VirtualModelRoute
  '/wardrobe': typeof WardrobeRoute
  '/store/$id': typeof StoreIdRoute
  '/store/items': typeof StoreItemsRoute
  '/store/package': typeof StorePackageRoute
  '/store/register': typeof StoreRegisterRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/matches'
    | '/profile'
    | '/store'
    | '/virtual-model'
    | '/wardrobe'
    | '/store/$id'
    | '/store/items'
    | '/store/package'
    | '/store/register'
    | '/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/matches'
    | '/profile'
    | '/virtual-model'
    | '/wardrobe'
    | '/store/$id'
    | '/store/items'
    | '/store/package'
    | '/store/register'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/matches'
    | '/profile'
    | '/store'
    | '/virtual-model'
    | '/wardrobe'
    | '/store/$id'
    | '/store/items'
    | '/store/package'
    | '/store/register'
    | '/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  StoreRoute: typeof StoreRouteWithChildren
  VirtualModelRoute: typeof VirtualModelRoute
  WardrobeRoute: typeof WardrobeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-model': {
      id: '/virtual-model'
      path: '/virtual-model'
      fullPath: '/virtual-model'
      preLoaderRoute: typeof VirtualModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/register': {
      id: '/store/register'
      path: '/register'
      fullPath: '/store/register'
      preLoaderRoute: typeof StoreRegisterRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/package': {
      id: '/store/package'
      path: '/package'
      fullPath: '/store/package'
      preLoaderRoute: typeof StorePackageRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/items': {
      id: '/store/items'
      path: '/items'
      fullPath: '/store/items'
      preLoaderRoute: typeof StoreItemsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface StoreRouteChildren {
  StoreIdRoute: typeof StoreIdRoute
  StoreItemsRoute: typeof StoreItemsRoute
  StorePackageRoute: typeof StorePackageRoute
  StoreRegisterRoute: typeof StoreRegisterRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreIdRoute: StoreIdRoute,
  StoreItemsRoute: StoreItemsRoute,
  StorePackageRoute: StorePackageRoute,
  StoreRegisterRoute: StoreRegisterRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  StoreRoute: StoreRouteWithChildren,
  VirtualModelRoute: VirtualModelRoute,
  WardrobeRoute: WardrobeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
